# Generated by Django 5.2.8 on 2025-12-30 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(help_text='Refresh token do Zoho (não expira, gerado uma vez)', max_length=500, unique=True)),
                ('access_token', models.TextField(blank=True, help_text='Access token atual do Zoho (expira em ~1 hora)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data/hora de expiração do access token', null=True)),
                ('scope', models.CharField(blank=True, help_text='Scopes autorizados no Zoho', max_length=500)),
                ('api_domain', models.URLField(default='https://www.zohoapis.com', help_text='API domain do Zoho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Zoho',
                'verbose_name_plural': 'Tokens Zoho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único da solicitação', max_length=64, unique=True)),
                ('system', models.CharField(choices=[('zoho', 'Zoho'), ('ad', 'Active Directory'), ('both', 'Zoho e AD')], help_text='Sistema onde a senha será resetada', max_length=20)),
                ('identifier', models.CharField(help_text='Email ou identificador usado na solicitação', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('otp_validated', 'OTP Validado'), ('completed', 'Concluído'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', help_text='Status atual da solicitação', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Data/hora de expiração da solicitação (padrão: 1 hora)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Data/hora de conclusão do reset', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que solicitou (se identificado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Reset de Senha',
                'verbose_name_plural': 'Solicitações de Reset de Senha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código OTP de 6 dígitos', max_length=6)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], help_text='Método usado para enviar OTP (SMS ou Email)', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('validated', 'Validado'), ('expired', 'Expirado'), ('exceeded_attempts', 'Tentativas Excedidas')], default='pending', help_text='Status atual do token OTP', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Número de tentativas de validação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Data/hora de expiração do OTP (padrão: 10 minutos)')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Data/hora de validação do OTP', null=True)),
                ('reset_request', models.ForeignKey(help_text='Solicitação de reset relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to='accounts.passwordresetrequest')),
            ],
            options={
                'verbose_name': 'Token OTP',
                'verbose_name_plural': 'Tokens OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('zoho', 'Zoho'), ('ad', 'Active Directory')], help_text='Sistema externo (Zoho ou AD)', max_length=20)),
                ('zoho_email', models.EmailField(blank=True, help_text='Email da conta Zoho', max_length=254, null=True)),
                ('ad_username', models.CharField(blank=True, help_text='Username no Active Directory', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone para SMS OTP (formato internacional)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuário do Django vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='system_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de Sistema',
                'verbose_name_plural': 'Contas de Sistema',
                'ordering': ['user', 'system'],
                'unique_together': {('user', 'system')},
            },
        ),
    ]
