# Generated by Django 5.2.8 on 2025-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticket_glpi_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['name'], 'verbose_name': 'Anexo GLPI', 'verbose_name_plural': 'Anexos GLPI'},
        ),
        migrations.AlterModelOptions(
            name='glpicategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria GLPI', 'verbose_name_plural': 'Categorias GLPI'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='glpi_ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID do Ticket GLPI'),
        ),
    ]
