# Generated by Django 5.2.8 on 2025-11-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attachment_options_alter_glpicategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket GLPI', 'verbose_name_plural': 'Tickets GLPI'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='glpi_ticket_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do Ticket GLPI'),
        ),
    ]
