# Generated by Django 5.2.8 on 2025-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_options_remove_ticket_glpi_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='glpi_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Incidente'), (2, 'Requisição')], help_text='Tipo informado pelo GLPI (1=Incidente, 2=Requisição)', null=True),
        ),
    ]
