# Generated by Django 5.2.8 on 2025-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_glpicategory_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='classification_confidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='classification_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
