# Generated by Django 5.2.8 on 2025-12-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_classification_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_path', models.CharField(help_text="Caminho completo sugerido (ex.: 'TI > Requisição > Administrativo > Montagem de Setup > Transmissão/Vídeo Conferência')", max_length=1024)),
                ('ticket_title', models.CharField(help_text='Título do ticket para contexto', max_length=255)),
                ('ticket_content', models.TextField(blank=True, help_text='Conteúdo do ticket para contexto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', help_text='Status da sugestão', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais sobre a sugestão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.ForeignKey(help_text='Ticket que gerou esta sugestão', on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Sugestão de Categoria',
                'verbose_name_plural': 'Sugestões de Categorias',
                'ordering': ['-created_at'],
            },
        ),
    ]
