# Generated by Django 5.2.8 on 2025-12-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categorysuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], help_text='Resposta do usuário: sim ou não', max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Comentário opcional do usuário sobre o atendimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(help_text='Ticket relacionado à pesquisa de satisfação', on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Pesquisa de Satisfação',
                'verbose_name_plural': 'Pesquisas de Satisfação',
                'ordering': ['-created_at'],
            },
        ),
    ]
