# Generated by Django 5.2.8 on 2025-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_satisfactionsurvey'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='satisfactionsurvey',
            constraint=models.UniqueConstraint(fields=('ticket',), name='unique_survey_per_ticket'),
        ),
    ]
