# Generated by Django 5.2.8 on 2025-12-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_satisfactionsurvey_unique_survey_per_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfactionsurvey',
            name='response',
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muito Insatisfeito'), (2, '2 - Insatisfeito'), (3, '3 - Neutro'), (4, '4 - Satisfeito'), (5, '5 - Muito Satisfeito')], help_text='Nota de satisfação do usuário (1 a 5)', null=True),
        ),
    ]