# Generated by Django 5.2.8 on 2025-12-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_satisfactionsurvey_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Muito Insatisfeito'), (2, '2 - Insatisfeito'), (3, '3 - Neutro'), (4, '4 - Satisfeito'), (5, '5 - Muito Satisfeito')], default=3, help_text='Nota de satisfação do usuário (1 a 5)'),
            preserve_default=False,
        ),
    ]
