# Generated by Django 5.2.8 on 2025-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_satisfactionsurvey_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='token',
            field=models.CharField(blank=True, help_text='Token único de segurança para validar a pesquisa (gerado na primeira requisição)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração do token (padrão: 30 dias após criação)', null=True),
        ),
    ]
