# Generated by Django 5.2.8 on 2025-12-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_satisfactionsurvey_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
