# Generated by Django 5.2.8 on 2025-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
