# Generated by Django 5.2.8 on 2025-12-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('conceitual', 'Conceitual'), ('operacional', 'Operacional'), ('troubleshooting', 'Troubleshooting')], help_text='Tipo do artigo (conceitual, operacional ou troubleshooting)', max_length=20)),
                ('category', models.CharField(help_text="Categoria da Base de Conhecimento (ex: 'RTV > AM > TI > Suporte > Técnicos > Jornal / Switcher')", max_length=1024)),
                ('context', models.TextField(help_text='Contexto do ambiente usado para gerar o artigo')),
                ('content', models.TextField(help_text='Conteúdo completo do artigo em Markdown')),
                ('content_html', models.TextField(help_text='Conteúdo do artigo convertido para HTML')),
                ('source', models.CharField(choices=[('preview', 'Preview Manual')], default='preview', help_text='Origem do artigo: preview manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artigo de Base de Conhecimento',
                'verbose_name_plural': 'Artigos de Base de Conhecimento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='source',
            field=models.CharField(choices=[('ticket', 'Ticket Real'), ('preview', 'Preview Manual')], default='ticket', help_text='Origem da sugestão: ticket real ou preview manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorysuggestion',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket que gerou esta sugestão (opcional para previews)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to='core.ticket'),
        ),
    ]
